import { NextAuthProvider } from '@/providers/auth'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import "./globals.css";
import Providers from './data/context/ThemeProvider';
import Footer from '@/components/Footer';
import { useSession } from 'next-auth/react';
import { useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import ToastProvider from '@/providers/toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mr. Fix It',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  }: {
    children: React.ReactNode
  }) {

  return (
    <html lang="en" >
      <Providers>
          <body className="bg-whiteBG dark:bg-darkBG">
            <NextAuthProvider>
              <ToastProvider>

              <Header />
              {children}

              <Footer />
              </ToastProvider>
            </NextAuthProvider>
            </body>
            </Providers>
    </html>
    // </SessionProvider>
  )
}
