import { NextAuthProvider } from '@/providers/auth'
import type { Metadata } from 'next'
import Link from 'next/link';
import { Inter } from 'next/font/google'
import ToastProvider from '@/providers/toast';
import Providers from './data/context/ThemeProvider';
import { useSession } from 'next-auth/react';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import "./globals.css";

import Header from '@/components/Header'
import Footer from '@/components/Footer';
import { EdgeStoreProvider } from '@/lib/edgestore';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mr. Fix It',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" >
      <Providers>
        <body className="bg-whiteBG dark:bg-darkBG">
          <NextAuthProvider>
            <ToastProvider>
              <div className="flex flex-col h-screen">
                <div>
                  <Header />
                </div>
                <div className='flex-1'>
                  <EdgeStoreProvider>{children}</EdgeStoreProvider></div>
                <Footer />
              </div>
            </ToastProvider>
          </NextAuthProvider>
        </body>
      </Providers>
    </html>
    // </SessionProvider>
  )
}
