-- AlterTable
ALTER TABLE "users" ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "image" SET DEFAULT '',
ALTER COLUMN "emailVerified" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "password" SET DEFAULT '';
